name: Node.js Package on github registry.

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@aissaoui-ahmed'
      - run: npm ci
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}" && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
