name: Node.js Package on npm registry.

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          scope: '@aissaoui-ahmed'
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}" && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}